# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trackr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trackr
    pod 'SwiftyJSON'
    pod 'Kingfisher', '4.9.0'
    pod 'Alamofire', '~> 4.8.2'
    pod 'KeychainSwift'
    pod 'CodableAlamofire'
    pod 'EFInternetIndicator'
    pod 'Wormholy'
    pod 'IQKeyboardManagerSwift'
    pod 'SkeletonView', '~> 1.4.2'
    pod 'RealmSwift'

end
